// Canonical list of all 114 surahs with ayah counts (Hafs).
// Used by the Phase C.1 hifz logger surah picker.

export interface SurahInfo {
  number: number;
  nameTransliterated: string;
  nameArabic: string;
  ayahCount: number;
}

export const SURAHS: ReadonlyArray<SurahInfo> = [
  { number: 1, nameTransliterated: "Al-Fatiha", nameArabic: "الفاتحة", ayahCount: 7 },
  { number: 2, nameTransliterated: "Al-Baqarah", nameArabic: "البقرة", ayahCount: 286 },
  { number: 3, nameTransliterated: "Aal-i-Imraan", nameArabic: "آل عمران", ayahCount: 200 },
  { number: 4, nameTransliterated: "An-Nisa", nameArabic: "النساء", ayahCount: 176 },
  { number: 5, nameTransliterated: "Al-Ma'idah", nameArabic: "المائدة", ayahCount: 120 },
  { number: 6, nameTransliterated: "Al-An'am", nameArabic: "الأنعام", ayahCount: 165 },
  { number: 7, nameTransliterated: "Al-A'raf", nameArabic: "الأعراف", ayahCount: 206 },
  { number: 8, nameTransliterated: "Al-Anfal", nameArabic: "الأنفال", ayahCount: 75 },
  { number: 9, nameTransliterated: "At-Tawbah", nameArabic: "التوبة", ayahCount: 129 },
  { number: 10, nameTransliterated: "Yunus", nameArabic: "يونس", ayahCount: 109 },
  { number: 11, nameTransliterated: "Hud", nameArabic: "هود", ayahCount: 123 },
  { number: 12, nameTransliterated: "Yusuf", nameArabic: "يوسف", ayahCount: 111 },
  { number: 13, nameTransliterated: "Ar-Ra'd", nameArabic: "الرعد", ayahCount: 43 },
  { number: 14, nameTransliterated: "Ibrahim", nameArabic: "إبراهيم", ayahCount: 52 },
  { number: 15, nameTransliterated: "Al-Hijr", nameArabic: "الحجر", ayahCount: 99 },
  { number: 16, nameTransliterated: "An-Nahl", nameArabic: "النحل", ayahCount: 128 },
  { number: 17, nameTransliterated: "Al-Isra", nameArabic: "الإسراء", ayahCount: 111 },
  { number: 18, nameTransliterated: "Al-Kahf", nameArabic: "الكهف", ayahCount: 110 },
  { number: 19, nameTransliterated: "Maryam", nameArabic: "مريم", ayahCount: 98 },
  { number: 20, nameTransliterated: "Ta-Ha", nameArabic: "طه", ayahCount: 135 },
  { number: 21, nameTransliterated: "Al-Anbiya", nameArabic: "الأنبياء", ayahCount: 112 },
  { number: 22, nameTransliterated: "Al-Hajj", nameArabic: "الحج", ayahCount: 78 },
  { number: 23, nameTransliterated: "Al-Mu'minun", nameArabic: "المؤمنون", ayahCount: 118 },
  { number: 24, nameTransliterated: "An-Nur", nameArabic: "النور", ayahCount: 64 },
  { number: 25, nameTransliterated: "Al-Furqan", nameArabic: "الفرقان", ayahCount: 77 },
  { number: 26, nameTransliterated: "Ash-Shu'ara", nameArabic: "الشعراء", ayahCount: 227 },
  { number: 27, nameTransliterated: "An-Naml", nameArabic: "النمل", ayahCount: 93 },
  { number: 28, nameTransliterated: "Al-Qasas", nameArabic: "القصص", ayahCount: 88 },
  { number: 29, nameTransliterated: "Al-Ankabut", nameArabic: "العنكبوت", ayahCount: 69 },
  { number: 30, nameTransliterated: "Ar-Rum", nameArabic: "الروم", ayahCount: 60 },
  { number: 31, nameTransliterated: "Luqman", nameArabic: "لقمان", ayahCount: 34 },
  { number: 32, nameTransliterated: "As-Sajdah", nameArabic: "السجدة", ayahCount: 30 },
  { number: 33, nameTransliterated: "Al-Ahzab", nameArabic: "الأحزاب", ayahCount: 73 },
  { number: 34, nameTransliterated: "Saba", nameArabic: "سبأ", ayahCount: 54 },
  { number: 35, nameTransliterated: "Fatir", nameArabic: "فاطر", ayahCount: 45 },
  { number: 36, nameTransliterated: "Ya-Sin", nameArabic: "يس", ayahCount: 83 },
  { number: 37, nameTransliterated: "As-Saffat", nameArabic: "الصافات", ayahCount: 182 },
  { number: 38, nameTransliterated: "Sad", nameArabic: "ص", ayahCount: 88 },
  { number: 39, nameTransliterated: "Az-Zumar", nameArabic: "الزمر", ayahCount: 75 },
  { number: 40, nameTransliterated: "Ghafir", nameArabic: "غافر", ayahCount: 85 },
  { number: 41, nameTransliterated: "Fussilat", nameArabic: "فصلت", ayahCount: 54 },
  { number: 42, nameTransliterated: "Ash-Shura", nameArabic: "الشورى", ayahCount: 53 },
  { number: 43, nameTransliterated: "Az-Zukhruf", nameArabic: "الزخرف", ayahCount: 89 },
  { number: 44, nameTransliterated: "Ad-Dukhan", nameArabic: "الدخان", ayahCount: 59 },
  { number: 45, nameTransliterated: "Al-Jathiyah", nameArabic: "الجاثية", ayahCount: 37 },
  { number: 46, nameTransliterated: "Al-Ahqaf", nameArabic: "الأحقاف", ayahCount: 35 },
  { number: 47, nameTransliterated: "Muhammad", nameArabic: "محمد", ayahCount: 38 },
  { number: 48, nameTransliterated: "Al-Fath", nameArabic: "الفتح", ayahCount: 29 },
  { number: 49, nameTransliterated: "Al-Hujurat", nameArabic: "الحجرات", ayahCount: 18 },
  { number: 50, nameTransliterated: "Qaf", nameArabic: "ق", ayahCount: 45 },
  { number: 51, nameTransliterated: "Adh-Dhariyat", nameArabic: "الذاريات", ayahCount: 60 },
  { number: 52, nameTransliterated: "At-Tur", nameArabic: "الطور", ayahCount: 49 },
  { number: 53, nameTransliterated: "An-Najm", nameArabic: "النجم", ayahCount: 62 },
  { number: 54, nameTransliterated: "Al-Qamar", nameArabic: "القمر", ayahCount: 55 },
  { number: 55, nameTransliterated: "Ar-Rahman", nameArabic: "الرحمن", ayahCount: 78 },
  { number: 56, nameTransliterated: "Al-Waqi'ah", nameArabic: "الواقعة", ayahCount: 96 },
  { number: 57, nameTransliterated: "Al-Hadid", nameArabic: "الحديد", ayahCount: 29 },
  { number: 58, nameTransliterated: "Al-Mujadilah", nameArabic: "المجادلة", ayahCount: 22 },
  { number: 59, nameTransliterated: "Al-Hashr", nameArabic: "الحشر", ayahCount: 24 },
  { number: 60, nameTransliterated: "Al-Mumtahanah", nameArabic: "الممتحنة", ayahCount: 13 },
  { number: 61, nameTransliterated: "As-Saff", nameArabic: "الصف", ayahCount: 14 },
  { number: 62, nameTransliterated: "Al-Jumu'ah", nameArabic: "الجمعة", ayahCount: 11 },
  { number: 63, nameTransliterated: "Al-Munafiqun", nameArabic: "المنافقون", ayahCount: 11 },
  { number: 64, nameTransliterated: "At-Taghabun", nameArabic: "التغابن", ayahCount: 18 },
  { number: 65, nameTransliterated: "At-Talaq", nameArabic: "الطلاق", ayahCount: 12 },
  { number: 66, nameTransliterated: "At-Tahrim", nameArabic: "التحريم", ayahCount: 12 },
  { number: 67, nameTransliterated: "Al-Mulk", nameArabic: "الملك", ayahCount: 30 },
  { number: 68, nameTransliterated: "Al-Qalam", nameArabic: "القلم", ayahCount: 52 },
  { number: 69, nameTransliterated: "Al-Haqqah", nameArabic: "الحاقة", ayahCount: 52 },
  { number: 70, nameTransliterated: "Al-Ma'arij", nameArabic: "المعارج", ayahCount: 44 },
  { number: 71, nameTransliterated: "Nuh", nameArabic: "نوح", ayahCount: 28 },
  { number: 72, nameTransliterated: "Al-Jinn", nameArabic: "الجن", ayahCount: 28 },
  { number: 73, nameTransliterated: "Al-Muzzammil", nameArabic: "المزمل", ayahCount: 20 },
  { number: 74, nameTransliterated: "Al-Muddaththir", nameArabic: "المدثر", ayahCount: 56 },
  { number: 75, nameTransliterated: "Al-Qiyamah", nameArabic: "القيامة", ayahCount: 40 },
  { number: 76, nameTransliterated: "Al-Insan", nameArabic: "الإنسان", ayahCount: 31 },
  { number: 77, nameTransliterated: "Al-Mursalat", nameArabic: "المرسلات", ayahCount: 50 },
  { number: 78, nameTransliterated: "An-Naba", nameArabic: "النبأ", ayahCount: 40 },
  { number: 79, nameTransliterated: "An-Nazi'at", nameArabic: "النازعات", ayahCount: 46 },
  { number: 80, nameTransliterated: "Abasa", nameArabic: "عبس", ayahCount: 42 },
  { number: 81, nameTransliterated: "At-Takwir", nameArabic: "التكوير", ayahCount: 29 },
  { number: 82, nameTransliterated: "Al-Infitar", nameArabic: "الإنفطار", ayahCount: 19 },
  { number: 83, nameTransliterated: "Al-Mutaffifin", nameArabic: "المطففين", ayahCount: 36 },
  { number: 84, nameTransliterated: "Al-Inshiqaq", nameArabic: "الإنشقاق", ayahCount: 25 },
  { number: 85, nameTransliterated: "Al-Buruj", nameArabic: "البروج", ayahCount: 22 },
  { number: 86, nameTransliterated: "At-Tariq", nameArabic: "الطارق", ayahCount: 17 },
  { number: 87, nameTransliterated: "Al-A'la", nameArabic: "الأعلى", ayahCount: 19 },
  { number: 88, nameTransliterated: "Al-Ghashiyah", nameArabic: "الغاشية", ayahCount: 26 },
  { number: 89, nameTransliterated: "Al-Fajr", nameArabic: "الفجر", ayahCount: 30 },
  { number: 90, nameTransliterated: "Al-Balad", nameArabic: "البلد", ayahCount: 20 },
  { number: 91, nameTransliterated: "Ash-Shams", nameArabic: "الشمس", ayahCount: 15 },
  { number: 92, nameTransliterated: "Al-Layl", nameArabic: "الليل", ayahCount: 21 },
  { number: 93, nameTransliterated: "Ad-Duha", nameArabic: "الضحى", ayahCount: 11 },
  { number: 94, nameTransliterated: "Ash-Sharh", nameArabic: "الشرح", ayahCount: 8 },
  { number: 95, nameTransliterated: "At-Tin", nameArabic: "التين", ayahCount: 8 },
  { number: 96, nameTransliterated: "Al-Alaq", nameArabic: "العلق", ayahCount: 19 },
  { number: 97, nameTransliterated: "Al-Qadr", nameArabic: "القدر", ayahCount: 5 },
  { number: 98, nameTransliterated: "Al-Bayyinah", nameArabic: "البينة", ayahCount: 8 },
  { number: 99, nameTransliterated: "Az-Zalzalah", nameArabic: "الزلزلة", ayahCount: 8 },
  { number: 100, nameTransliterated: "Al-Adiyat", nameArabic: "العاديات", ayahCount: 11 },
  { number: 101, nameTransliterated: "Al-Qari'ah", nameArabic: "القارعة", ayahCount: 11 },
  { number: 102, nameTransliterated: "At-Takathur", nameArabic: "التكاثر", ayahCount: 8 },
  { number: 103, nameTransliterated: "Al-Asr", nameArabic: "العصر", ayahCount: 3 },
  { number: 104, nameTransliterated: "Al-Humazah", nameArabic: "الهمزة", ayahCount: 9 },
  { number: 105, nameTransliterated: "Al-Fil", nameArabic: "الفيل", ayahCount: 5 },
  { number: 106, nameTransliterated: "Quraysh", nameArabic: "قريش", ayahCount: 4 },
  { number: 107, nameTransliterated: "Al-Ma'un", nameArabic: "الماعون", ayahCount: 7 },
  { number: 108, nameTransliterated: "Al-Kawthar", nameArabic: "الكوثر", ayahCount: 3 },
  { number: 109, nameTransliterated: "Al-Kafirun", nameArabic: "الكافرون", ayahCount: 6 },
  { number: 110, nameTransliterated: "An-Nasr", nameArabic: "النصر", ayahCount: 3 },
  { number: 111, nameTransliterated: "Al-Masad", nameArabic: "المسد", ayahCount: 5 },
  { number: 112, nameTransliterated: "Al-Ikhlas", nameArabic: "الإخلاص", ayahCount: 4 },
  { number: 113, nameTransliterated: "Al-Falaq", nameArabic: "الفلق", ayahCount: 5 },
  { number: 114, nameTransliterated: "An-Nas", nameArabic: "الناس", ayahCount: 6 },
];

export const getSurah = (n: number): SurahInfo | undefined =>
  SURAHS.find((s) => s.number === n);
