// =============================================================================
// gen-db-types.ts — regenerate the TypeScript Database type from live schema.
//
// Why:
//   Supabase JS swallows column-not-found errors into `null` + Error (see F8
//   in the QA findings: student.roll_number / class_subject.display_order were
//   silently returning empty result sets). Compile-time typing is the only
//   reliable defence.
//
// What it does:
//   1. Calls `npx supabase gen types typescript --project-id <ref> --schema public`
//   2. Writes the result to supabase/functions/_shared/db.ts
//   3. Exit code 1 if the file changed — CI uses this to fail the build when
//      someone adds a migration but forgets to regen types.
//
// Usage:
//   npx tsx scripts/gen-db-types.ts            # regenerate locally
//   npx tsx scripts/gen-db-types.ts --check    # fail if out of date (CI)
//
// Requires `SUPABASE_PROJECT_ID` in env (or it falls back to the config.toml
// project_id below).
// =============================================================================

import { spawnSync } from "node:child_process";
import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { dirname } from "node:path";

const PROJECT_ID = process.env.SUPABASE_PROJECT_ID ?? "ybrkbrrkcqpzpjnjdyib";
const OUT = "supabase/functions/_shared/db.ts";
const CHECK = process.argv.includes("--check");

const HEADER = `// AUTO-GENERATED by scripts/gen-db-types.ts — DO NOT EDIT BY HAND.
// Regenerate with: npx tsx scripts/gen-db-types.ts
// CI runs the same command with --check; if this file is dirty after a
// migration, the build fails.
//
// Project: ${PROJECT_ID}
//
`;

console.log(`[gen-db-types] generating from project ${PROJECT_ID}…`);

const r = spawnSync(
  "npx",
  [
    "--yes",
    "supabase",
    "gen",
    "types",
    "typescript",
    "--project-id",
    PROJECT_ID,
    "--schema",
    "public",
  ],
  { encoding: "utf8", shell: process.platform === "win32" },
);

if (r.status !== 0) {
  console.error("[gen-db-types] supabase CLI failed:");
  console.error(r.stderr || r.stdout);
  process.exit(2);
}

const body = HEADER + (r.stdout ?? "").trim() + "\n";

mkdirSync(dirname(OUT), { recursive: true });

const existing = existsSync(OUT) ? readFileSync(OUT, "utf8") : "";

if (CHECK) {
  if (existing.trim() !== body.trim()) {
    console.error(`[gen-db-types] ${OUT} is out of date.`);
    console.error("Run `npx tsx scripts/gen-db-types.ts` and commit the result.");
    process.exit(1);
  }
  console.log("[gen-db-types] up to date ✓");
  process.exit(0);
}

writeFileSync(OUT, body);
console.log(`[gen-db-types] wrote ${OUT} (${body.length} bytes)`);
