-- =============================================================================
-- School Pilot — Curriculum: relax legacy class_section_id requirements.
--
-- Phase 1D moved curriculum to (class_subject, academic_year), but the
-- original Phase CD schema still required class_section_id NOT NULL and
-- enforced UNIQUE(class_section_id, academic_year). That made the new
-- model impossible to use:
--   - The Phase 5 demo seed silently failed every curriculum insert
--     because it only writes class_subject_id (NOT NULL violation).
--   - Multiple subjects (Math + English + …) in the same section + year
--     can't all share a section row under the old UNIQUE.
--
-- This migration:
--   1. Drops NOT NULL on class_section_id (kept as a soft, optional link
--      for legacy per-section curricula).
--   2. Drops the old UNIQUE(class_section_id, academic_year) constraint.
--      The Phase 1D partial UNIQUE on (class_subject_id, academic_year)
--      WHERE class_subject_id IS NOT NULL (added by 0020) remains the
--      authoritative uniqueness rule.
--
-- Idempotent.
-- =============================================================================

ALTER TABLE curriculum
  ALTER COLUMN class_section_id DROP NOT NULL;

-- The old constraint name is autogenerated as <table>_<col1>_<col2>_key.
-- Drop defensively; multiple installs may have slightly different names.
ALTER TABLE curriculum
  DROP CONSTRAINT IF EXISTS curriculum_class_section_id_academic_year_key;

-- Some installs may have created an alternate name; try the common
-- variants too so this migration applies cleanly on every env we've
-- seen in the field.
DO $$
DECLARE
  con record;
BEGIN
  FOR con IN
    SELECT conname
    FROM   pg_constraint
    WHERE  conrelid = 'curriculum'::regclass
      AND  contype = 'u'
      AND  conkey @> ARRAY[
        (SELECT attnum FROM pg_attribute WHERE attrelid = 'curriculum'::regclass AND attname = 'class_section_id'),
        (SELECT attnum FROM pg_attribute WHERE attrelid = 'curriculum'::regclass AND attname = 'academic_year')
      ]::int2[]
  LOOP
    EXECUTE format('ALTER TABLE curriculum DROP CONSTRAINT %I', con.conname);
  END LOOP;
END$$;
