// Data for the "Guess the Prophet" game.
//
// IMPORTANT — REVIEW BEFORE PRODUCTION:
//   Every attribute below was set based on mainstream Sunni Islamic
//   understanding, but I'm an AI assistant and these facts about
//   Prophets are sensitive. Muneeb should verify the table against
//   an authoritative source (e.g. Tafsir Ibn Kathir's "Stories of
//   the Prophets", Maariful Quran, or a qualified scholar) before
//   the game ships to real users.
//
//   Where I'm uncertain, the attribute is set to `null` so the game
//   answers "I don't know" rather than guessing. Each `null` has a
//   `// TODO verify:` comment explaining what I was unsure about.
//
// Game rules the data must support:
//   - System picks a Prophet, kid asks yes/no questions, kid guesses.
//   - Each QUESTION points to one ATTRIBUTE on the Prophet record.
//   - Answer is `attributes[attribute]` — true / false / null.
//   - null = "I don't know — try a different question."
//
// To add a new question:
//   1. Add the attribute key to PROPHETS records (with true/false/null per Prophet).
//   2. Add a row to QUESTIONS pointing to that attribute key.
//
// To add a Prophet: append to PROPHETS. Make sure attributes object
// has every key in the attribute schema (use null for unknown).

// =============================================================================
// Attribute schema — order documented here so reviewers can scan vertically
// =============================================================================
// Era:
//   first_human, lived_unusually_long, lived_before_ibrahim,
//   last_prophet
// Family:
//   was_descendant_of_ibrahim, had_brother_who_was_also_prophet,
//   had_son_who_became_prophet, was_father_of_a_prophet
// Mission:
//   one_of_ulu_al_azm,         (the 5 great messengers: Nuh, Ibrahim, Musa, Isa, Muhammad)
//   received_major_book,       (Tawrah, Zaboor, Injil, Quran)
//   received_quran,
//   sent_to_arabia,            (Hud→Ad, Salih→Thamud, Muhammad→Quraysh)
//   sent_to_bani_israel
// Location:
//   lived_in_arabia, lived_in_egypt, lived_in_palestine_or_levant
// Miracles & marked events:
//   built_an_ark, was_thrown_into_fire, was_swallowed_by_whale,
//   spoke_to_allah_directly, stick_became_snake, could_command_jinn,
//   could_understand_animals, was_born_without_father,
//   was_taken_up_alive, was_a_king, was_a_minister_or_high_official,
//   was_tested_with_severe_illness
// =============================================================================

export interface ProphetRecord {
  id: string;
  name: string;
  nameArabic: string;
  englishName: string | null;
  /** Each value: true | false | null (null = "I don't know") */
  attributes: Record<string, boolean | null>;
}

export const PROPHETS: ProphetRecord[] = [
  {
    id: "adam",
    name: "Adam",
    nameArabic: "آدم",
    englishName: "Adam",
    attributes: {
      first_human: true,
      lived_unusually_long: true,
      lived_before_ibrahim: true,
      last_prophet: false,
      was_descendant_of_ibrahim: false,
      had_brother_who_was_also_prophet: false,
      had_son_who_became_prophet: null, // TODO verify: Shith is a Prophet per some traditions
      was_father_of_a_prophet: null,    // TODO verify same
      one_of_ulu_al_azm: false,
      received_major_book: false,        // received scrolls, not one of the 4 major books
      received_quran: false,
      sent_to_arabia: false,
      sent_to_bani_israel: false,
      lived_in_arabia: false,
      lived_in_egypt: false,
      lived_in_palestine_or_levant: false,
      built_an_ark: false,
      was_thrown_into_fire: false,
      was_swallowed_by_whale: false,
      spoke_to_allah_directly: true,     // spoke with Allah in Jannah and after
      stick_became_snake: false,
      could_command_jinn: false,
      could_understand_animals: false,
      was_born_without_father: true,     // created directly by Allah, no parents
      was_taken_up_alive: false,
      was_a_king: false,
      was_a_minister_or_high_official: false,
      was_tested_with_severe_illness: false,
    },
  },
  {
    id: "idris",
    name: "Idris",
    nameArabic: "إدريس",
    englishName: "Enoch",
    attributes: {
      first_human: false,
      lived_unusually_long: true,
      lived_before_ibrahim: true,
      last_prophet: false,
      was_descendant_of_ibrahim: false,
      had_brother_who_was_also_prophet: false,
      had_son_who_became_prophet: false,
      was_father_of_a_prophet: false,
      one_of_ulu_al_azm: false,
      received_major_book: false,
      received_quran: false,
      sent_to_arabia: false,
      sent_to_bani_israel: false,
      lived_in_arabia: false,
      lived_in_egypt: false,
      lived_in_palestine_or_levant: false,
      built_an_ark: false,
      was_thrown_into_fire: false,
      was_swallowed_by_whale: false,
      spoke_to_allah_directly: null,     // TODO verify
      stick_became_snake: false,
      could_command_jinn: false,
      could_understand_animals: false,
      was_born_without_father: false,
      was_taken_up_alive: true,          // raised by Allah per Qur'an 19:57
      was_a_king: false,
      was_a_minister_or_high_official: false,
      was_tested_with_severe_illness: false,
    },
  },
  {
    id: "nuh",
    name: "Nuh",
    nameArabic: "نوح",
    englishName: "Noah",
    attributes: {
      first_human: false,
      lived_unusually_long: true,        // 950 years per Qur'an 29:14
      lived_before_ibrahim: true,
      last_prophet: false,
      was_descendant_of_ibrahim: false,
      had_brother_who_was_also_prophet: false,
      had_son_who_became_prophet: false,
      was_father_of_a_prophet: false,
      one_of_ulu_al_azm: true,
      received_major_book: false,
      received_quran: false,
      sent_to_arabia: false,
      sent_to_bani_israel: false,
      lived_in_arabia: false,
      lived_in_egypt: false,
      lived_in_palestine_or_levant: false,
      built_an_ark: true,
      was_thrown_into_fire: false,
      was_swallowed_by_whale: false,
      spoke_to_allah_directly: null,
      stick_became_snake: false,
      could_command_jinn: false,
      could_understand_animals: false,
      was_born_without_father: false,
      was_taken_up_alive: false,
      was_a_king: false,
      was_a_minister_or_high_official: false,
      was_tested_with_severe_illness: false,
    },
  },
  {
    id: "hud",
    name: "Hud",
    nameArabic: "هود",
    englishName: null,
    attributes: {
      first_human: false,
      lived_unusually_long: false,
      lived_before_ibrahim: true,
      last_prophet: false,
      was_descendant_of_ibrahim: false,
      had_brother_who_was_also_prophet: false,
      had_son_who_became_prophet: false,
      was_father_of_a_prophet: false,
      one_of_ulu_al_azm: false,
      received_major_book: false,
      received_quran: false,
      sent_to_arabia: true,              // to the people of 'Ad
      sent_to_bani_israel: false,
      lived_in_arabia: true,
      lived_in_egypt: false,
      lived_in_palestine_or_levant: false,
      built_an_ark: false,
      was_thrown_into_fire: false,
      was_swallowed_by_whale: false,
      spoke_to_allah_directly: null,
      stick_became_snake: false,
      could_command_jinn: false,
      could_understand_animals: false,
      was_born_without_father: false,
      was_taken_up_alive: false,
      was_a_king: false,
      was_a_minister_or_high_official: false,
      was_tested_with_severe_illness: false,
    },
  },
  {
    id: "salih",
    name: "Salih",
    nameArabic: "صالح",
    englishName: null,
    attributes: {
      first_human: false,
      lived_unusually_long: false,
      lived_before_ibrahim: true,
      last_prophet: false,
      was_descendant_of_ibrahim: false,
      had_brother_who_was_also_prophet: false,
      had_son_who_became_prophet: false,
      was_father_of_a_prophet: false,
      one_of_ulu_al_azm: false,
      received_major_book: false,
      received_quran: false,
      sent_to_arabia: true,              // to the people of Thamud
      sent_to_bani_israel: false,
      lived_in_arabia: true,
      lived_in_egypt: false,
      lived_in_palestine_or_levant: false,
      built_an_ark: false,
      was_thrown_into_fire: false,
      was_swallowed_by_whale: false,
      spoke_to_allah_directly: null,
      stick_became_snake: false,
      could_command_jinn: false,
      could_understand_animals: false,
      was_born_without_father: false,
      was_taken_up_alive: false,
      was_a_king: false,
      was_a_minister_or_high_official: false,
      was_tested_with_severe_illness: false,
    },
  },
  {
    id: "ibrahim",
    name: "Ibrahim",
    nameArabic: "إبراهيم",
    englishName: "Abraham",
    attributes: {
      first_human: false,
      lived_unusually_long: false,
      lived_before_ibrahim: false,
      last_prophet: false,
      was_descendant_of_ibrahim: false,
      had_brother_who_was_also_prophet: false,
      had_son_who_became_prophet: true,  // Ismail + Ishaq
      was_father_of_a_prophet: true,
      one_of_ulu_al_azm: true,
      received_major_book: false,        // received suhuf (scrolls), not one of the 4 major
      received_quran: false,
      sent_to_arabia: false,
      sent_to_bani_israel: false,
      lived_in_arabia: false,            // lived in Iraq → Sham → built Ka'bah; complex
      lived_in_egypt: false,
      lived_in_palestine_or_levant: true,
      built_an_ark: false,
      was_thrown_into_fire: true,
      was_swallowed_by_whale: false,
      spoke_to_allah_directly: null,
      stick_became_snake: false,
      could_command_jinn: false,
      could_understand_animals: false,
      was_born_without_father: false,
      was_taken_up_alive: false,
      was_a_king: false,
      was_a_minister_or_high_official: false,
      was_tested_with_severe_illness: false,
    },
  },
  {
    id: "lut",
    name: "Lut",
    nameArabic: "لوط",
    englishName: "Lot",
    attributes: {
      first_human: false,
      lived_unusually_long: false,
      lived_before_ibrahim: false,
      last_prophet: false,
      was_descendant_of_ibrahim: false,  // nephew, not descendant
      had_brother_who_was_also_prophet: false,
      had_son_who_became_prophet: false,
      was_father_of_a_prophet: false,
      one_of_ulu_al_azm: false,
      received_major_book: false,
      received_quran: false,
      sent_to_arabia: false,
      sent_to_bani_israel: false,
      lived_in_arabia: false,
      lived_in_egypt: false,
      lived_in_palestine_or_levant: true,
      built_an_ark: false,
      was_thrown_into_fire: false,
      was_swallowed_by_whale: false,
      spoke_to_allah_directly: null,
      stick_became_snake: false,
      could_command_jinn: false,
      could_understand_animals: false,
      was_born_without_father: false,
      was_taken_up_alive: false,
      was_a_king: false,
      was_a_minister_or_high_official: false,
      was_tested_with_severe_illness: false,
    },
  },
  {
    id: "ismail",
    name: "Ismail",
    nameArabic: "إسماعيل",
    englishName: "Ishmael",
    attributes: {
      first_human: false,
      lived_unusually_long: false,
      lived_before_ibrahim: false,
      last_prophet: false,
      was_descendant_of_ibrahim: true,
      had_brother_who_was_also_prophet: true,  // Ishaq
      had_son_who_became_prophet: false,        // descendants include Muhammad ﷺ but not direct son
      was_father_of_a_prophet: false,           // TODO verify: depends on definition
      one_of_ulu_al_azm: false,
      received_major_book: false,
      received_quran: false,
      sent_to_arabia: true,
      sent_to_bani_israel: false,
      lived_in_arabia: true,             // settled in Makkah
      lived_in_egypt: false,
      lived_in_palestine_or_levant: false,
      built_an_ark: false,
      was_thrown_into_fire: false,
      was_swallowed_by_whale: false,
      spoke_to_allah_directly: null,
      stick_became_snake: false,
      could_command_jinn: false,
      could_understand_animals: false,
      was_born_without_father: false,
      was_taken_up_alive: false,
      was_a_king: false,
      was_a_minister_or_high_official: false,
      was_tested_with_severe_illness: false,
    },
  },
  {
    id: "ishaq",
    name: "Ishaq",
    nameArabic: "إسحاق",
    englishName: "Isaac",
    attributes: {
      first_human: false,
      lived_unusually_long: false,
      lived_before_ibrahim: false,
      last_prophet: false,
      was_descendant_of_ibrahim: true,
      had_brother_who_was_also_prophet: true,  // Ismail
      had_son_who_became_prophet: true,         // Yaqub
      was_father_of_a_prophet: true,
      one_of_ulu_al_azm: false,
      received_major_book: false,
      received_quran: false,
      sent_to_arabia: false,
      sent_to_bani_israel: false,        // pre-existed Bani Israel
      lived_in_arabia: false,
      lived_in_egypt: false,
      lived_in_palestine_or_levant: true,
      built_an_ark: false,
      was_thrown_into_fire: false,
      was_swallowed_by_whale: false,
      spoke_to_allah_directly: null,
      stick_became_snake: false,
      could_command_jinn: false,
      could_understand_animals: false,
      was_born_without_father: false,
      was_taken_up_alive: false,
      was_a_king: false,
      was_a_minister_or_high_official: false,
      was_tested_with_severe_illness: false,
    },
  },
  {
    id: "yaqub",
    name: "Yaqub",
    nameArabic: "يعقوب",
    englishName: "Jacob",
    attributes: {
      first_human: false,
      lived_unusually_long: false,
      lived_before_ibrahim: false,
      last_prophet: false,
      was_descendant_of_ibrahim: true,
      had_brother_who_was_also_prophet: false,
      had_son_who_became_prophet: true,  // Yusuf
      was_father_of_a_prophet: true,
      one_of_ulu_al_azm: false,
      received_major_book: false,
      received_quran: false,
      sent_to_arabia: false,
      sent_to_bani_israel: null,         // TODO verify: was the patriarch (Israel), but sent-to relationship is different
      lived_in_arabia: false,
      lived_in_egypt: false,             // moved to Egypt later in life
      lived_in_palestine_or_levant: true,
      built_an_ark: false,
      was_thrown_into_fire: false,
      was_swallowed_by_whale: false,
      spoke_to_allah_directly: null,
      stick_became_snake: false,
      could_command_jinn: false,
      could_understand_animals: false,
      was_born_without_father: false,
      was_taken_up_alive: false,
      was_a_king: false,
      was_a_minister_or_high_official: false,
      was_tested_with_severe_illness: false,
    },
  },
  {
    id: "yusuf",
    name: "Yusuf",
    nameArabic: "يوسف",
    englishName: "Joseph",
    attributes: {
      first_human: false,
      lived_unusually_long: false,
      lived_before_ibrahim: false,
      last_prophet: false,
      was_descendant_of_ibrahim: true,
      had_brother_who_was_also_prophet: false,
      had_son_who_became_prophet: false,
      was_father_of_a_prophet: false,
      one_of_ulu_al_azm: false,
      received_major_book: false,
      received_quran: false,
      sent_to_arabia: false,
      sent_to_bani_israel: null,
      lived_in_arabia: false,
      lived_in_egypt: true,
      lived_in_palestine_or_levant: true, // born there, lived in Egypt
      built_an_ark: false,
      was_thrown_into_fire: false,
      was_swallowed_by_whale: false,
      spoke_to_allah_directly: null,
      stick_became_snake: false,
      could_command_jinn: false,
      could_understand_animals: false,
      was_born_without_father: false,
      was_taken_up_alive: false,
      was_a_king: false,
      was_a_minister_or_high_official: true, // Aziz / treasury of Egypt
      was_tested_with_severe_illness: false,
    },
  },
  {
    id: "ayyub",
    name: "Ayyub",
    nameArabic: "أيوب",
    englishName: "Job",
    attributes: {
      first_human: false,
      lived_unusually_long: false,
      lived_before_ibrahim: false,       // post-Ibrahim per most traditions
      last_prophet: false,
      was_descendant_of_ibrahim: true,   // descendant per common tradition
      had_brother_who_was_also_prophet: false,
      had_son_who_became_prophet: false,
      was_father_of_a_prophet: false,
      one_of_ulu_al_azm: false,
      received_major_book: false,
      received_quran: false,
      sent_to_arabia: false,
      sent_to_bani_israel: false,
      lived_in_arabia: false,
      lived_in_egypt: false,
      lived_in_palestine_or_levant: true,
      built_an_ark: false,
      was_thrown_into_fire: false,
      was_swallowed_by_whale: false,
      spoke_to_allah_directly: null,
      stick_became_snake: false,
      could_command_jinn: false,
      could_understand_animals: false,
      was_born_without_father: false,
      was_taken_up_alive: false,
      was_a_king: false,
      was_a_minister_or_high_official: false,
      was_tested_with_severe_illness: true,  // famous for sabr through illness
    },
  },
  {
    id: "shuayb",
    name: "Shuayb",
    nameArabic: "شعيب",
    englishName: "Jethro",
    attributes: {
      first_human: false,
      lived_unusually_long: false,
      lived_before_ibrahim: false,
      last_prophet: false,
      was_descendant_of_ibrahim: null,   // TODO verify
      had_brother_who_was_also_prophet: false,
      had_son_who_became_prophet: false,
      was_father_of_a_prophet: false,
      one_of_ulu_al_azm: false,
      received_major_book: false,
      received_quran: false,
      sent_to_arabia: false,             // to Madyan
      sent_to_bani_israel: false,
      lived_in_arabia: null,             // Madyan ~northwest Arabia depending on definition
      lived_in_egypt: false,
      lived_in_palestine_or_levant: false,
      built_an_ark: false,
      was_thrown_into_fire: false,
      was_swallowed_by_whale: false,
      spoke_to_allah_directly: null,
      stick_became_snake: false,
      could_command_jinn: false,
      could_understand_animals: false,
      was_born_without_father: false,
      was_taken_up_alive: false,
      was_a_king: false,
      was_a_minister_or_high_official: false,
      was_tested_with_severe_illness: false,
    },
  },
  {
    id: "musa",
    name: "Musa",
    nameArabic: "موسى",
    englishName: "Moses",
    attributes: {
      first_human: false,
      lived_unusually_long: false,
      lived_before_ibrahim: false,
      last_prophet: false,
      was_descendant_of_ibrahim: true,
      had_brother_who_was_also_prophet: true,  // Harun
      had_son_who_became_prophet: false,
      was_father_of_a_prophet: false,
      one_of_ulu_al_azm: true,
      received_major_book: true,          // Tawrah
      received_quran: false,
      sent_to_arabia: false,
      sent_to_bani_israel: true,
      lived_in_arabia: false,
      lived_in_egypt: true,
      lived_in_palestine_or_levant: false,
      built_an_ark: false,
      was_thrown_into_fire: false,
      was_swallowed_by_whale: false,
      spoke_to_allah_directly: true,      // Kalim Allah
      stick_became_snake: true,
      could_command_jinn: false,
      could_understand_animals: false,
      was_born_without_father: false,
      was_taken_up_alive: false,
      was_a_king: false,
      was_a_minister_or_high_official: false,
      was_tested_with_severe_illness: false,
    },
  },
  {
    id: "harun",
    name: "Harun",
    nameArabic: "هارون",
    englishName: "Aaron",
    attributes: {
      first_human: false,
      lived_unusually_long: false,
      lived_before_ibrahim: false,
      last_prophet: false,
      was_descendant_of_ibrahim: true,
      had_brother_who_was_also_prophet: true, // Musa
      had_son_who_became_prophet: false,
      was_father_of_a_prophet: false,
      one_of_ulu_al_azm: false,
      received_major_book: false,        // assisted Musa, didn't receive own book
      received_quran: false,
      sent_to_arabia: false,
      sent_to_bani_israel: true,
      lived_in_arabia: false,
      lived_in_egypt: true,
      lived_in_palestine_or_levant: false,
      built_an_ark: false,
      was_thrown_into_fire: false,
      was_swallowed_by_whale: false,
      spoke_to_allah_directly: null,
      stick_became_snake: false,
      could_command_jinn: false,
      could_understand_animals: false,
      was_born_without_father: false,
      was_taken_up_alive: false,
      was_a_king: false,
      was_a_minister_or_high_official: false,
      was_tested_with_severe_illness: false,
    },
  },
  {
    id: "dhul-kifl",
    name: "Dhul-Kifl",
    nameArabic: "ذو الكفل",
    englishName: null,
    attributes: {
      first_human: false,
      lived_unusually_long: false,
      lived_before_ibrahim: null,
      last_prophet: false,
      was_descendant_of_ibrahim: null,   // TODO verify
      had_brother_who_was_also_prophet: false,
      had_son_who_became_prophet: false,
      was_father_of_a_prophet: false,
      one_of_ulu_al_azm: false,
      received_major_book: false,
      received_quran: false,
      sent_to_arabia: false,
      sent_to_bani_israel: null,
      lived_in_arabia: false,
      lived_in_egypt: false,
      lived_in_palestine_or_levant: null,
      built_an_ark: false,
      was_thrown_into_fire: false,
      was_swallowed_by_whale: false,
      spoke_to_allah_directly: null,
      stick_became_snake: false,
      could_command_jinn: false,
      could_understand_animals: false,
      was_born_without_father: false,
      was_taken_up_alive: false,
      was_a_king: false,
      was_a_minister_or_high_official: false,
      was_tested_with_severe_illness: false,
    },
  },
  {
    id: "dawud",
    name: "Dawud",
    nameArabic: "داود",
    englishName: "David",
    attributes: {
      first_human: false,
      lived_unusually_long: false,
      lived_before_ibrahim: false,
      last_prophet: false,
      was_descendant_of_ibrahim: true,
      had_brother_who_was_also_prophet: false,
      had_son_who_became_prophet: true,  // Sulayman
      was_father_of_a_prophet: true,
      one_of_ulu_al_azm: false,
      received_major_book: true,         // Zaboor
      received_quran: false,
      sent_to_arabia: false,
      sent_to_bani_israel: true,
      lived_in_arabia: false,
      lived_in_egypt: false,
      lived_in_palestine_or_levant: true,
      built_an_ark: false,
      was_thrown_into_fire: false,
      was_swallowed_by_whale: false,
      spoke_to_allah_directly: null,
      stick_became_snake: false,
      could_command_jinn: false,
      could_understand_animals: null,    // mountains glorified with him; birds too — TODO verify
      was_born_without_father: false,
      was_taken_up_alive: false,
      was_a_king: true,
      was_a_minister_or_high_official: false,
      was_tested_with_severe_illness: false,
    },
  },
  {
    id: "sulayman",
    name: "Sulayman",
    nameArabic: "سليمان",
    englishName: "Solomon",
    attributes: {
      first_human: false,
      lived_unusually_long: false,
      lived_before_ibrahim: false,
      last_prophet: false,
      was_descendant_of_ibrahim: true,
      had_brother_who_was_also_prophet: false,
      had_son_who_became_prophet: false,
      was_father_of_a_prophet: false,
      one_of_ulu_al_azm: false,
      received_major_book: false,        // inherited from Dawud per common understanding
      received_quran: false,
      sent_to_arabia: false,
      sent_to_bani_israel: true,
      lived_in_arabia: false,
      lived_in_egypt: false,
      lived_in_palestine_or_levant: true,
      built_an_ark: false,
      was_thrown_into_fire: false,
      was_swallowed_by_whale: false,
      spoke_to_allah_directly: null,
      stick_became_snake: false,
      could_command_jinn: true,
      could_understand_animals: true,    // ants, hoopoe
      was_born_without_father: false,
      was_taken_up_alive: false,
      was_a_king: true,
      was_a_minister_or_high_official: false,
      was_tested_with_severe_illness: false,
    },
  },
  {
    id: "ilyas",
    name: "Ilyas",
    nameArabic: "إلياس",
    englishName: "Elijah",
    attributes: {
      first_human: false,
      lived_unusually_long: false,
      lived_before_ibrahim: false,
      last_prophet: false,
      was_descendant_of_ibrahim: true,
      had_brother_who_was_also_prophet: false,
      had_son_who_became_prophet: false,
      was_father_of_a_prophet: false,
      one_of_ulu_al_azm: false,
      received_major_book: false,
      received_quran: false,
      sent_to_arabia: false,
      sent_to_bani_israel: true,
      lived_in_arabia: false,
      lived_in_egypt: false,
      lived_in_palestine_or_levant: true,
      built_an_ark: false,
      was_thrown_into_fire: false,
      was_swallowed_by_whale: false,
      spoke_to_allah_directly: null,
      stick_became_snake: false,
      could_command_jinn: false,
      could_understand_animals: false,
      was_born_without_father: false,
      was_taken_up_alive: false,
      was_a_king: false,
      was_a_minister_or_high_official: false,
      was_tested_with_severe_illness: false,
    },
  },
  {
    id: "al-yasa",
    name: "Al-Yasa",
    nameArabic: "اليسع",
    englishName: "Elisha",
    attributes: {
      first_human: false,
      lived_unusually_long: false,
      lived_before_ibrahim: false,
      last_prophet: false,
      was_descendant_of_ibrahim: true,
      had_brother_who_was_also_prophet: false,
      had_son_who_became_prophet: false,
      was_father_of_a_prophet: false,
      one_of_ulu_al_azm: false,
      received_major_book: false,
      received_quran: false,
      sent_to_arabia: false,
      sent_to_bani_israel: true,
      lived_in_arabia: false,
      lived_in_egypt: false,
      lived_in_palestine_or_levant: true,
      built_an_ark: false,
      was_thrown_into_fire: false,
      was_swallowed_by_whale: false,
      spoke_to_allah_directly: null,
      stick_became_snake: false,
      could_command_jinn: false,
      could_understand_animals: false,
      was_born_without_father: false,
      was_taken_up_alive: false,
      was_a_king: false,
      was_a_minister_or_high_official: false,
      was_tested_with_severe_illness: false,
    },
  },
  {
    id: "yunus",
    name: "Yunus",
    nameArabic: "يونس",
    englishName: "Jonah",
    attributes: {
      first_human: false,
      lived_unusually_long: false,
      lived_before_ibrahim: false,
      last_prophet: false,
      was_descendant_of_ibrahim: null,   // TODO verify
      had_brother_who_was_also_prophet: false,
      had_son_who_became_prophet: false,
      was_father_of_a_prophet: false,
      one_of_ulu_al_azm: false,
      received_major_book: false,
      received_quran: false,
      sent_to_arabia: false,
      sent_to_bani_israel: false,        // sent to Nineveh (people of Yunus)
      lived_in_arabia: false,
      lived_in_egypt: false,
      lived_in_palestine_or_levant: false,
      built_an_ark: false,
      was_thrown_into_fire: false,
      was_swallowed_by_whale: true,
      spoke_to_allah_directly: null,
      stick_became_snake: false,
      could_command_jinn: false,
      could_understand_animals: false,
      was_born_without_father: false,
      was_taken_up_alive: false,
      was_a_king: false,
      was_a_minister_or_high_official: false,
      was_tested_with_severe_illness: false,
    },
  },
  {
    id: "zakariya",
    name: "Zakariya",
    nameArabic: "زكريا",
    englishName: "Zechariah",
    attributes: {
      first_human: false,
      lived_unusually_long: true,        // had Yahya in old age per Qur'an
      lived_before_ibrahim: false,
      last_prophet: false,
      was_descendant_of_ibrahim: true,
      had_brother_who_was_also_prophet: false,
      had_son_who_became_prophet: true,  // Yahya
      was_father_of_a_prophet: true,
      one_of_ulu_al_azm: false,
      received_major_book: false,
      received_quran: false,
      sent_to_arabia: false,
      sent_to_bani_israel: true,
      lived_in_arabia: false,
      lived_in_egypt: false,
      lived_in_palestine_or_levant: true,
      built_an_ark: false,
      was_thrown_into_fire: false,
      was_swallowed_by_whale: false,
      spoke_to_allah_directly: null,
      stick_became_snake: false,
      could_command_jinn: false,
      could_understand_animals: false,
      was_born_without_father: false,
      was_taken_up_alive: false,
      was_a_king: false,
      was_a_minister_or_high_official: false,
      was_tested_with_severe_illness: false,
    },
  },
  {
    id: "yahya",
    name: "Yahya",
    nameArabic: "يحيى",
    englishName: "John",
    attributes: {
      first_human: false,
      lived_unusually_long: false,
      lived_before_ibrahim: false,
      last_prophet: false,
      was_descendant_of_ibrahim: true,
      had_brother_who_was_also_prophet: false,
      had_son_who_became_prophet: false,
      was_father_of_a_prophet: false,
      one_of_ulu_al_azm: false,
      received_major_book: false,
      received_quran: false,
      sent_to_arabia: false,
      sent_to_bani_israel: true,
      lived_in_arabia: false,
      lived_in_egypt: false,
      lived_in_palestine_or_levant: true,
      built_an_ark: false,
      was_thrown_into_fire: false,
      was_swallowed_by_whale: false,
      spoke_to_allah_directly: null,
      stick_became_snake: false,
      could_command_jinn: false,
      could_understand_animals: false,
      was_born_without_father: false,
      was_taken_up_alive: false,
      was_a_king: false,
      was_a_minister_or_high_official: false,
      was_tested_with_severe_illness: false,
    },
  },
  {
    id: "isa",
    name: "Isa",
    nameArabic: "عيسى",
    englishName: "Jesus",
    attributes: {
      first_human: false,
      lived_unusually_long: false,
      lived_before_ibrahim: false,
      last_prophet: false,
      was_descendant_of_ibrahim: true,
      had_brother_who_was_also_prophet: false,
      had_son_who_became_prophet: false,
      was_father_of_a_prophet: false,
      one_of_ulu_al_azm: true,
      received_major_book: true,         // Injil
      received_quran: false,
      sent_to_arabia: false,
      sent_to_bani_israel: true,
      lived_in_arabia: false,
      lived_in_egypt: false,
      lived_in_palestine_or_levant: true,
      built_an_ark: false,
      was_thrown_into_fire: false,
      was_swallowed_by_whale: false,
      spoke_to_allah_directly: null,
      stick_became_snake: false,
      could_command_jinn: false,
      could_understand_animals: false,
      was_born_without_father: true,
      was_taken_up_alive: true,           // Qur'an 4:158
      was_a_king: false,
      was_a_minister_or_high_official: false,
      was_tested_with_severe_illness: false,
    },
  },
  {
    id: "muhammad",
    name: "Muhammad ﷺ",
    nameArabic: "محمد ﷺ",
    englishName: "Muhammad",
    attributes: {
      first_human: false,
      lived_unusually_long: false,
      lived_before_ibrahim: false,
      last_prophet: true,
      was_descendant_of_ibrahim: true,
      had_brother_who_was_also_prophet: false,
      had_son_who_became_prophet: false,
      was_father_of_a_prophet: false,
      one_of_ulu_al_azm: true,
      received_major_book: true,         // Qur'an
      received_quran: true,
      sent_to_arabia: true,
      sent_to_bani_israel: false,         // Quraysh primarily; ultimately to all humanity
      lived_in_arabia: true,
      lived_in_egypt: false,
      lived_in_palestine_or_levant: false,
      built_an_ark: false,
      was_thrown_into_fire: false,
      was_swallowed_by_whale: false,
      spoke_to_allah_directly: null,     // Mi'raj — TODO consider with care
      stick_became_snake: false,
      could_command_jinn: false,
      could_understand_animals: false,
      was_born_without_father: false,    // father Abdullah died before birth — TODO verify intent
      was_taken_up_alive: false,
      was_a_king: false,
      was_a_minister_or_high_official: false,
      was_tested_with_severe_illness: false,
    },
  },
];

// =============================================================================
// QUESTIONS — what kids tap to ask. Each maps to one attribute.
// =============================================================================
export interface QuestionRecord {
  id: string;
  text: string;
  attribute: string;
  category: QuestionCategory;
}

export type QuestionCategory = "era" | "family" | "mission" | "location" | "miracles" | "other";

export const QUESTION_CATEGORIES: { id: QuestionCategory; label: string; emoji: string }[] = [
  { id: "era",       label: "When?",      emoji: "🕰️" },
  { id: "location",  label: "Where?",     emoji: "🗺️" },
  { id: "family",    label: "Family",     emoji: "👨‍👩‍👧‍👦" },
  { id: "mission",   label: "Mission",    emoji: "📖" },
  { id: "miracles",  label: "Miracles",   emoji: "✨" },
  { id: "other",     label: "Other",      emoji: "❓" },
];

export const QUESTIONS: QuestionRecord[] = [
  // Era
  { id: "q-first-human",        text: "Was this Prophet the first human?",                                attribute: "first_human",            category: "era" },
  { id: "q-lived-long",         text: "Did this Prophet live an unusually long life?",                    attribute: "lived_unusually_long",   category: "era" },
  { id: "q-before-ibrahim",     text: "Did this Prophet live before Prophet Ibrahim (Abraham)?",          attribute: "lived_before_ibrahim",   category: "era" },
  { id: "q-last-prophet",       text: "Was this Prophet the last and final Prophet?",                     attribute: "last_prophet",           category: "era" },

  // Family
  { id: "q-descendant-ibrahim", text: "Was this Prophet a descendant of Ibrahim (Abraham)?",              attribute: "was_descendant_of_ibrahim", category: "family" },
  { id: "q-brother-prophet",    text: "Did this Prophet have a brother who was also a Prophet?",          attribute: "had_brother_who_was_also_prophet", category: "family" },
  { id: "q-son-prophet",        text: "Did this Prophet have a son who became a Prophet?",                attribute: "had_son_who_became_prophet", category: "family" },
  { id: "q-father-of-prophet",  text: "Was this Prophet the father of another Prophet?",                  attribute: "was_father_of_a_prophet", category: "family" },

  // Mission
  { id: "q-ulu-al-azm",         text: "Was this Prophet one of the 5 great messengers (Ulu Al-Azm)?",     attribute: "one_of_ulu_al_azm",      category: "mission" },
  { id: "q-major-book",         text: "Did this Prophet receive a major scripture (Tawrah, Zaboor, Injil, or Qur'an)?", attribute: "received_major_book", category: "mission" },
  { id: "q-quran",              text: "Did this Prophet receive the Qur'an?",                             attribute: "received_quran",         category: "mission" },
  { id: "q-arabia-sent",        text: "Was this Prophet sent to people living in Arabia?",                attribute: "sent_to_arabia",         category: "mission" },
  { id: "q-bani-israel",        text: "Was this Prophet sent to Bani Israel (the Children of Israel)?",   attribute: "sent_to_bani_israel",    category: "mission" },

  // Location
  { id: "q-lived-arabia",       text: "Did this Prophet live in Arabia?",                                  attribute: "lived_in_arabia",        category: "location" },
  { id: "q-lived-egypt",        text: "Did this Prophet live in Egypt?",                                   attribute: "lived_in_egypt",         category: "location" },
  { id: "q-lived-levant",       text: "Did this Prophet live in Palestine or the Levant area?",            attribute: "lived_in_palestine_or_levant", category: "location" },

  // Miracles
  { id: "q-ark",                text: "Did this Prophet build a great ark?",                              attribute: "built_an_ark",           category: "miracles" },
  { id: "q-fire",               text: "Was this Prophet thrown into a fire and saved by Allah?",          attribute: "was_thrown_into_fire",   category: "miracles" },
  { id: "q-whale",              text: "Was this Prophet swallowed by a whale (great fish)?",              attribute: "was_swallowed_by_whale", category: "miracles" },
  { id: "q-spoke-allah",        text: "Did Allah speak to this Prophet directly?",                        attribute: "spoke_to_allah_directly", category: "miracles" },
  { id: "q-stick-snake",        text: "Did this Prophet's stick turn into a snake?",                      attribute: "stick_became_snake",     category: "miracles" },
  { id: "q-jinn",               text: "Could this Prophet command jinn?",                                 attribute: "could_command_jinn",     category: "miracles" },
  { id: "q-animals",            text: "Could this Prophet understand the speech of animals?",             attribute: "could_understand_animals", category: "miracles" },
  { id: "q-no-father",          text: "Was this Prophet born without a father?",                          attribute: "was_born_without_father", category: "miracles" },
  { id: "q-taken-up",           text: "Was this Prophet taken up alive (not having died)?",               attribute: "was_taken_up_alive",     category: "miracles" },

  // Other
  { id: "q-king",               text: "Was this Prophet a king?",                                          attribute: "was_a_king",             category: "other" },
  { id: "q-minister",           text: "Was this Prophet a minister or high official?",                    attribute: "was_a_minister_or_high_official", category: "other" },
  { id: "q-illness",            text: "Was this Prophet tested with a severe illness?",                   attribute: "was_tested_with_severe_illness", category: "other" },
];

// Quick lookup helpers
export const PROPHETS_BY_ID = new Map(PROPHETS.map((p) => [p.id, p]));
export const QUESTIONS_BY_ID = new Map(QUESTIONS.map((q) => [q.id, q]));

/** Returns 'yes' / 'no' / 'unknown' for the asked question on the chosen prophet. */
export function answerQuestion(prophetId: string, questionId: string): "yes" | "no" | "unknown" {
  const prophet = PROPHETS_BY_ID.get(prophetId);
  const question = QUESTIONS_BY_ID.get(questionId);
  if (!prophet || !question) return "unknown";
  const val = prophet.attributes[question.attribute];
  if (val === true) return "yes";
  if (val === false) return "no";
  return "unknown";
}
